<a href="https://colab.research.google.com/github/stephenbrutch/Python-Machine-Learning-Tutorial-Codes/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Link: https://www.youtube.com/watch?v=tpCFfeUEGs8 . Will cover most fundamental concepts of tensors using Tensorflow. More specifcally going to cover:
1.   Introduction to tensors
2.   Getting information from tensors
3.   Manipulating tensors
4.   Tensors and NumPy
5.   Using @tf.function(a way to speed up your regular python functions)
6.   Using GPUs with TensorFlow
7.   Exercises to try



In [ ]:
#INTRO TO TENSORS
#######################################


#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

#Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

#Create a vector
vector=tf.constant([10,10])
vector

#Check the dimensions of the vector
vector.ndim

#Create a matrix (has more than 1 dimension)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

#check the  number of dimensions of a vector
matrix.ndim

#Create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16) #specifc the data type with dtype
another_matrix

#Whats the dimensions of another matrix
another_matrix.ndim

#Lets create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12],
                    [13,14,15],
                    [16,17,18]]])
tensor
tensor.ndim



2.12.0


3

Analysis of Lines (1-50)

1.   Scalar is a single number
2.   Vector is a number with direction
3.   Matrix is a 2-dimensional array of numbers
4.   Tensor is a n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)



In [ ]:
#Creating tensors with tf.variable


#Create the same tensor with tf.variable as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

#Lets change one of the elements in our changeable tensor
changeable_tensor[0].assign(7) #need to use .assign


#unchangebale tensors using tf.constant can not be changed using .assign()

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Create random tensors
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

#Check if they are equal
random_1 , random_2 , random_1 == random_2 #they are equal because of .from_seed(n) where n is the same number for 2 different tensor variables. .set_seed=42 sets the random as the same thing

#Shuffle the order of the tensor (ex. in case first 1000 images are pictures of bananas and next 1000 images are pictures of apples, the NN may learn what only bananas look like bc thats
#what its only trained on == shuffle data so that it learns both at the same time)
not_shuffled=tf.constant([[10,7],
                         [3,4],
                         [2,5]])

#Shuffle our non_shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)
#not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Analysis of lines(1-19) above: If we want the shuffled tensors to be in the same order: set the global level random seed as well as the operation level random seed. ex:

* tf.random.set_seed(42) #set global level random seed
*   tensor1=tf.constant([define tensor])
*   tensor1_shuffled=tf.random.shuffle(tensor1,seed=42) #set operator seed








In [ ]:
#Other ways to make tensors
#Create a tensor of all 1's
tf.ones([10,7])

#Create a tensor of all 0's
tf.zeros(shape=(3,4))





<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The main difference between NumpPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
#You can also turn NumPy arrays into tensors
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32) #create a NumPy array between 1 and 25
A=tf.constant(numpy_A,shape=(2,3,4)) #change form of numpy array into tensor
B=tf.constant(numpy_A)
A,B




(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)



1.   get a tensor shape: tensor.shape
2.   get a tensor rank/# of tensor dimensions: tensor.ndim
3.   access a particular dimension of a tensor: tensor[0], tensor[:,1]
4.   get total number of items in a tensor: tf.size(tensor)



In [ ]:
#Getting more information from tensors
#Create a rank 4 tensor
rank_4_tensor=tf.zeros(shape=(2,3,4,5)) #Think of tensors as a stack of matrices. 2 splits the 6 matrices into 2 matrices. 3 is the number of matrices in each. 4 is the number of rows in each. 5 is the number of columns in each
rank_4_tensor #4 dimensions bc 4 numbers labeled (2,3,4,5)
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

#Get various attribute of our tensor
print("datatype of every element:",rank_4_tensor.dtype)
print("number of dimensions:",rank_4_tensor.ndim)
print("Shape of tensor:",rank_4_tensor.shape)
print("Elements along the 0 axis:",rank_4_tensor.shape[0])
print("Elements along the last axis:",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank_4_tensor))
print("Total number of elements in our tensor:",tf.size(rank_4_tensor).numpy()) #use .numpy to simplify what that output looks like



datatype of every element: <dtype: 'float32'>
number of dimensions: 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


Tensors can be index just like Python lists

In [ ]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2] #tensor slicing

#Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

#Create a rank 2 tensor (2 dimensions)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.ndim

#get the last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

#Add in extra dimension to our rank_2_tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]

#Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) #-1 means expand the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

Tensor Operations

In [ ]:
#You can add values to a tensor using the addition operator
tensor=tf.constant([[10,7],
                    [3,4]])
tensor * 10 #element wise operations

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
#Original tensor is unchanged tho
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#We can use the built-in function in tensorflow too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(tensor,-10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

Matrix/Tensor multiplcation

1.   tf.matmul
2.   tf.tensordot
3.   @



In [ ]:
#Matrix multiplcation in tensorflow
print(tensor)
tf.linalg.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix multiplication with python @ operator
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
X=tf.constant([[1,2],
               [3,4],
              [5,6]])
Y=tf.constant([[7,8],
               [9,10],
              [11,12]])
tf.transpose(X)@Y
tf.matmul(tf.transpose(X),Y)
tf.tensordot(tf.transpose(X),Y,axes=1)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Changing the data type of the tensor

In [ ]:
#Create a new tensor with default data type (float32)
B=tf.constant([1.7,4.3])
B.dtype
C=tf.constant([7,10])
C.dtype

#Change from float32 to float16 (changing the precision)
D=tf.cast(B,dtype=tf.float16)
D,D.dtype

#Change from int32 to float32
E=tf.cast(C,dtype=tf.float32)
E
E_float16=tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

Aggregate tensors: condensing them from multiple values down to a smaller amount of values

In [ ]:
#Get the absolute values
D=tf.constant([-7,-10])
D
tf.abs(D)

#Get the minimum, maximum, mean, sum of a tensor
#Create a random tensor with values between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E
tf.size(E),E.shape,E.ndim

#Find the minimum
E, tf.reduce_min(E)

#Find the maximum
E,tf.reduce_max(E)

#Find the mean
E,tf.reduce_mean(E)

#Find the sum
E,tf.reduce_sum(E)

#Find the standard deviation.
E_std=tf.cast(E,dtype=tf.float32)
E,tf.math.reduce_std(E_std)

#Find the variance
import tensorflow_probability as tfp
E,tfp.stats.variance(E)

#Find the positional maximum and minimum of a tensor
F=tf.constant([[1,8,3],
              [7,2,6],
              [4,5,9]])
F,tf.argmax(F)



G=tf.random.uniform(shape=[50])
#Find positional max
tf.argmax(G)
#Index on our largest value
G[tf.argmax(G)]
#Find max value
tf.reduce_max(G)
G[tf.argmax(G)]==tf.reduce_max(G)

#*******Use argmin for minimum



<tf.Tensor: shape=(), dtype=bool, numpy=True>

Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
H=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
H
H.shape
H_squeezed=tf.squeeze(H)
H_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

One hot encoding

In [ ]:
#Create a list of indices
some_list=[0,1,2,3]
#One hot encode our list of indices
tf.one_hot(some_list,len(some_list))

#Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="one",off_value="zero")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'one', b'zero', b'zero', b'zero'],
       [b'zero', b'one', b'zero', b'zero'],
       [b'zero', b'zero', b'one', b'zero'],
       [b'zero', b'zero', b'zero', b'one']], dtype=object)>

In [ ]:
#Squaring, log, square root
I=tf.range(1,10)
I
#Square each individual index
tf.square(I)

#Find the squareroot. Requires float type
tf.sqrt(tf.cast(I,dtype=tf.float32))

#Find the log
tf.math.log(tf.cast(I,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors and numpy

In [ ]:
#Create a tensor directly from a numpy array
J=tf.constant(np.array([3.,7.,10.]))
J

#Convert tensor back to numpy array
np.array(J),type(np.array(J))

#Convert tensor J to numpy array
J.numpy(),type(J.numpy())

J=tf.constant([3.])
J.numpy()[0]

#The default data types of each are slightly different
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])

#Check the datatypes of each
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)